### ISSUE TITLE
Email integration

### ISSUE THREAD

**Issue by arunkpatra** [arunkpatra/reloadly-services#4]
# Email integration

Implement Email integration using Amazon SES (other service providers in the future).

## Design Goals

- This should be a dropin solution. Enable Email support using Spring Boot auto-configuration
- Should be loosely coupled with the Email provider, it should be totally transparent to plugin another provider and swap out Amazon SES.
- Suitable configuration options must be exposed.

## Usage

Auto-configuration should kick in once following dependency is added to the classpath

```
<dependency>
    <groupId>com.reloadly</groupId>
    <artifactId>email-integration</artifactId>
    <version>1.0.0</version>
</dependency>
```

User can configuration the component as follows via application prope:rties in any Spring Boot app:

```
reloadly:
  integration:
    email:
      ses:
        enabled: true
        region: ap-south-1
        dry-run: true
```
