### ISSUE TITLE
Swagger UI Integration

### ISSUE THREAD

**Issue by arunkpatra** [arunkpatra/reloadly-services#5]
# Swagger UI integration

See: https://swagger.io/tools/swagger-ui/

Implement Email integration using Amazon SES (other service providers in the future).

## Design Goals

- This should be a dropin solution. Enable Swagger UI using Spring Boot auto-configuration
- Suitable configuration options must be exposed.

## Usage

Auto-configuration should kick in once following dependency is added to the classpath

```
<dependency>
    <groupId>com.reloadly</groupId>
    <artifactId>swagger-ui-integration</artifactId>
    <version>1.0.0</version>
</dependency>
```

User can configuration the component as follows via application properties in any Spring Boot app:

```
reloadly:
  integration:
    swagger:
      enabled: true
      api-title: Reloadly Authentication Services API
      api-description: Reloadly Authentication Services API
      api-version: 1.0.0
      base-url: /
      host: localhost:9090
      base-package: com.reloadly.auth.controller
      api-terms-of-service-url: https://reloadly.com/termsofservice
      license: Copyright reloadly.com
      license-url: https://reloadly.com/license
      contact:
        email: info@reloadly.com
        name: Reloadly Customer Service
        url: https://reloadly.com
```
